- hosts: localhost
  become: true
  
  tasks:
  - name: Install Kerberos dependencies dnf
    dnf:
      name:
      - '@Development Tools'
      - python3-devel
      - krb5-devel
      - python3-kerberos
      state: latest

  - name: Install Kerberos dependencies pip
    pip:
      name: 
      - pywinrm[kerberos]
      state: latest

